export enum Variant {
  DEFAULT = "DEFAULT",
  DISABLED = "DISABLED",
  INFO = "INFO",
  POSITIVE = "POSITIVE",
  WARNING = "WARNING",
  NEGATIVE = "NEGATIVE"
}

export enum Size {
  SMALL = "SMALL",
  NORMAL = "NORMAL",
  LARGE = "LARGE",
  EXTRA_LARGE = "EXTRA_LARGE"
}

export enum ErrorState {
  NONE = "NONE",
  RESOURCE_NOT_LOADING = "RESOURCE_NOT_LOADING",
  COURSE_NOT_FOUND = "COURSE_NOT_FOUND",
  CHECKPOINT_NOT_FOUND = "CHECKPOINT_NOT_FOUND",
  TOTAL_PANIC = "TOTAL_PANIC",
  NO_SEARCH_RESULTS = "NO_SEARCH_RESULTS"
}
export enum Direction {
  HORIZONTAL = "HORIZONTAL",
  VERTICAL = "VERTICAL",
  UP = "UP",
  DOWN = "DOWN"
}

export enum Affordance {
  NONE = "NONE",
  CHECKABLE = "CHECKABLE",
  UNCHECKABLE = "UNCHECKABLE",
  CLOSEABLE = "CLOSEABLE",
  EXPANDABLE = "EXPANDABLE",
  SHRINKABLE = "SHRINKABLE",
  SELECTABLE = "SELECTABLE"
}

export enum Alignment {
  START = "START",
  END = "END",
  FULL = "FULL",
  CENTER = "CENTER"
}
