export enum Variant {
  DEFAULT = "DEFAULT",
  DISABLED = "DISABLED",
  INFO = "INFO",
  POSITIVE = "POSITIVE",
  WARNING = "WARNING",
  NEGATIVE = "NEGATIVE"
}

export enum Size {
  SMALL = "SMALL",
  NORMAL = "NORMAL",
  LARGE = "LARGE",
  EXTRA_LARGE = "EXTRA_LARGE"
}

export enum ErrorStates {
  DEFAULT = "DEFAULT",
  RESOURCE_NOT_LOADING = "RESOURCE_NOT_LOADING",
  COURSE_NOT_FOUND = "COURSE_NOT_FOUND",
  CHECKPOINT_NOT_FOUND = "CHECKPOINT_NOT_FOUND",
  TOTAL_PANIC = "TOTAL_PANIC",
  NO_SEARCH_RESULTS = "NO_SEARCH_RESULTS"
}
